set(_AMENT_PACKAGE_NAME "uav_visual_landing")
set(uav_visual_landing_VERSION "0.0.0")
set(uav_visual_landing_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(uav_visual_landing_BUILD_DEPENDS "libopencv-dev" "libopencv-contrib-dev" "rclcpp" "px4_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "cv_bridge" "image_transport")
set(uav_visual_landing_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(uav_visual_landing_BUILD_EXPORT_DEPENDS "rclcpp" "px4_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "cv_bridge" "image_transport")
set(uav_visual_landing_BUILDTOOL_EXPORT_DEPENDS )
set(uav_visual_landing_EXEC_DEPENDS "libopencv-dev" "libopencv-contrib-dev" "rosidl_default_runtime" "rclcpp" "px4_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "cv_bridge" "image_transport")
set(uav_visual_landing_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gtest")
set(uav_visual_landing_GROUP_DEPENDS )
set(uav_visual_landing_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(uav_visual_landing_DEPRECATED "")
set(uav_visual_landing_EXPORT_TAGS)
list(APPEND uav_visual_landing_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
