set(_AMENT_PACKAGE_NAME "uav_mode_supervisor")
set(uav_mode_supervisor_VERSION "0.0.0")
set(uav_mode_supervisor_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(uav_mode_supervisor_BUILD_DEPENDS "diagnostic_msgs" "rclcpp" "relative_position_fusion" "std_msgs" "std_srvs" "uav_visual_landing")
set(uav_mode_supervisor_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(uav_mode_supervisor_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "rclcpp" "relative_position_fusion" "std_msgs" "std_srvs" "uav_visual_landing")
set(uav_mode_supervisor_BUILDTOOL_EXPORT_DEPENDS )
set(uav_mode_supervisor_EXEC_DEPENDS "rosidl_default_runtime" "diagnostic_msgs" "rclcpp" "relative_position_fusion" "std_msgs" "std_srvs" "uav_visual_landing")
set(uav_mode_supervisor_TEST_DEPENDS "ament_cmake_gtest")
set(uav_mode_supervisor_GROUP_DEPENDS )
set(uav_mode_supervisor_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(uav_mode_supervisor_DEPRECATED "")
set(uav_mode_supervisor_EXPORT_TAGS)
list(APPEND uav_mode_supervisor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
