set(_AMENT_PACKAGE_NAME "uav_bridge")
set(uav_bridge_VERSION "0.0.0")
set(uav_bridge_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(uav_bridge_BUILD_DEPENDS "libopencv-dev" "rclcpp" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "tf2" "tf2_ros" "quadrotor_msgs" "px4_msgs")
set(uav_bridge_BUILDTOOL_DEPENDS "ament_cmake")
set(uav_bridge_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "tf2" "tf2_ros" "quadrotor_msgs" "px4_msgs")
set(uav_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(uav_bridge_EXEC_DEPENDS "libopencv-dev" "rclcpp" "sensor_msgs" "geometry_msgs" "nav_msgs" "std_msgs" "std_srvs" "tf2" "tf2_ros" "quadrotor_msgs" "px4_msgs")
set(uav_bridge_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gtest")
set(uav_bridge_GROUP_DEPENDS )
set(uav_bridge_MEMBER_OF_GROUPS )
set(uav_bridge_DEPRECATED "")
set(uav_bridge_EXPORT_TAGS)
list(APPEND uav_bridge_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
