set(_AMENT_PACKAGE_NAME "uav_description")
set(uav_description_VERSION "0.1.0")
set(uav_description_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(uav_description_BUILD_DEPENDS )
set(uav_description_BUILDTOOL_DEPENDS "ament_cmake")
set(uav_description_BUILD_EXPORT_DEPENDS )
set(uav_description_BUILDTOOL_EXPORT_DEPENDS )
set(uav_description_EXEC_DEPENDS "xacro")
set(uav_description_TEST_DEPENDS )
set(uav_description_GROUP_DEPENDS )
set(uav_description_MEMBER_OF_GROUPS )
set(uav_description_DEPRECATED "")
set(uav_description_EXPORT_TAGS)
list(APPEND uav_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
